---
- name: kopiowanie kluczy
  hosts: webservers
  become: true
  vars_files:
    - vault/oci_config.yml


  tasks:
    - name: tworzenie oci hunter dr
      ansible.builtin.file:
        path: "/home/wolos/oci-instance-hunter/"
        state: directory
        owner: wolos
        group: wolos

    - name: tworzenie .oci dir
      ansible.builtin.file:
        path: "/home/wolos/.oci"
        state: directory
        mode: "0700"
        owner: wolos
        group: wolos


    - name: kopiowanie .env
      ansible.builtin.copy:
        src: "/Users/wolos/Documents/projekt devops/oci-instance-hunter/.env"
        dest: "/home/wolos/oci-instance-hunter/.env"
        mode: "0600"
        owner: wolos
        group: wolos

    - name: kopiowanie oci.pem
      ansible.builtin.copy:
        src: "/Users/wolos/.oci/kluczOCI-CLD.pem"
        dest: "/home/wolos/.oci/kluczOCI-CLD.pem"
        mode: "0600"
        owner: wolos
        group: wolos

    - name: utworzenie config dla oci-instance-hunter
      ansible.builtin.copy:
        content: |
          [DEFAULT]
          user={{ oci_user_ocid }}
          fingerprint={{ oci_fingerprint }}
          key_file=/home/wolos/.oci/kluczOCI-CLD.pem
          tenancy={{ oci_tenancy_ocid }}
          region={{ oci_region }}
          pass_phrase=n/a
        dest: "/home/wolos/.oci/config"
        mode: "0600"
        owner: wolos
        group: wolos
